import SearchHeader from '@/components/SearchHeader';

export const metadata = {
  title: 'Google Search Clone',
  description: 'Generated by create next app',
};

export default function SearchLayout({ children }) {
  return (
    <div>
      <SearchHeader />
      {children}
    </div>
  );
}
